# Generated by Django 4.2.23 on 2025-09-15 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=20)),
                ('section_image', models.ImageField(upload_to='sectionimg/')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_img', models.ImageField(upload_to='productimg/')),
                ('product_price', models.IntegerField()),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='shoppingapp.section')),
            ],
        ),
    ]
