# Generated by Django 4.2.23 on 2025-09-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0004_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='completeorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('House_number', models.PositiveIntegerField()),
                ('Street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('Zip_code', models.IntegerField()),
            ],
        ),
    ]
