# Generated by Django 4.2.23 on 2025-09-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0005_completeorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completeorder',
            old_name='Name',
            new_name='username',
        ),
    ]
