# Generated by Django 4.2.23 on 2025-09-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0006_rename_name_completeorder_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeorder',
            name='Payment_type',
            field=models.TextField(choices=[('card', 'card'), ('COD (cash on delivery)', 'COD (cash on delivery)'), ('upi', 'upi')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
