# Generated by Django 4.2.23 on 2025-09-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0007_completeorder_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeorder',
            name='Payment_type',
            field=models.TextField(choices=[('card', 'card'), ('COD (cash on delivery)', 'COD (cash on delivery)'), ('upi', 'upi')], default='card', max_length=100),
        ),
    ]
