# Generated by Django 4.2.7 on 2025-09-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0008_alter_completeorder_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeorder',
            name='state',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
