# Generated by Django 4.2.7 on 2025-09-24 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0011_updateprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='updateprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.completeorder'),
            preserve_default=False,
        ),
    ]
