# Generated by Django 4.2.23 on 2025-09-24 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0013_alter_updateprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.completeorder'),
        ),
    ]
