# Generated by Django 4.2.23 on 2025-09-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0014_alter_updateprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='updateprofile',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='updateprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='updateprofile',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='updateprofile',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
