# Generated by Django 4.2.23 on 2025-09-24 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0015_remove_updateprofile_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updateprofile',
            old_name='user',
            new_name='username',
        ),
    ]
