# Generated by Django 4.2.23 on 2025-09-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0016_rename_user_updateprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateprofile',
            name='password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
