# Generated by Django 4.2.23 on 2025-10-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0018_completeorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeorder',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
