# Generated by Django 4.2.23 on 2025-10-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0019_alter_completeorder_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeorder',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
