# Generated by Django 4.2.23 on 2025-10-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0020_alter_completeorder_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeorder',
            name='Payment_type',
            field=models.TextField(choices=[('card', 'card')], default='card', max_length=100),
        ),
    ]
